name: math
description: A sample command-line application.
# version: 1.0.0
# homepage: https://bunin.in
# author: Timofey Bunin <timmpw@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  ansicolor: ^1.0.2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
